<?php

/**
 * Created by PhpStorm.
 * User: 12807
 * Date: 2017/7/3
 * Time: 10:53
 */

namespace app\home\model;

use think\Db;
use think\Model;

class IndexModel extends Model
{
    protected $table = 'user';

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function getOneData()
    {
        $desc = Db::table($this->table)
            ->select();
        return $desc;
    }
}